### ISSUE TITLE
Why can the orthonormal basis x' of π be fixed horizontal?

### ISSUE THREAD

**Issue by xbliuhnu** [Zongwei97/Depth-Adapted-CNN#3]
Thanks for your amazing work. Here is my question when I understand the definition of the orthonormal basis (x', y') on π. Why can x' be fixed horizontal and not other direction? or can y' be fixed as vertical? what is the reason? does it affects the experiments?
Thank you.

**Comment by Zongwei97** [comment]
Hello,
Sorry for getting you late.
You can or fix x' as horizontal, or fix y' as vertical, but not both at the same time.
Empirically, we particularly fixed x' because it yields slightly better result in our preliminary work. But the difference is small

**Comment by xbliuhnu** [comment]
@Zongwei97 
I get it, thanks!
